[storage]
driver = "vfs"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
# Default settings for rootless storage path overrides will automatically be computed
# under user home directory (~/.local/share/containers/storage) by podman.
